name: Update README Every Hour

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C++ Code
      run: g++ -std=c++17 main.cpp -o updater

    - name: Run Updater
      run: ./updater

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        rm -f readme.md
        
        git add README.md || true
        
        if git diff --staged --quiet; then
          echo "No changes detected in README.md, skipping commit."
        else
          git commit -m "Update README with alive counter"
          git push
        fi




  
